### ISSUE TITLE
handles Lists<T> within POCO objects

### ISSUE THREAD

**Issue by BKSpurgeon** [mganss/ExcelMapper#2]
Hi there

thank you for your mapper.

Is there any ability to map lists within custom objects?

rgds

Ben

**Comment by mganss** [comment]
Currently no. How would you map a list of objects to a single cell? AFAIK Excel has no notion of a list/array cell type so you'd have to rely on a custom mapping scheme, e.g. a string containing the list's items separated by comma, semicolon etc. You'd have to provide for escaping because the list's items might contain the separator and escape characters. It might be best to allow a cell to contain JSON and map that 😄
